//
//  ViewController.m
//  F2W3-MapKitProject
//
//  Created by Leonardo Lee on 5/21/14.
//  Copyright (c) 2014 Leonardo Lee. All rights reserved.
//

#import "ViewController.h"
#import <MapKit/MapKit.h>
#import <CoreLocation/CoreLocation.h>
#import "Directions.h"

@interface ViewController () <CLLocationManagerDelegate, UISearchDisplayDelegate, UISearchBarDelegate>


@property (nonatomic, strong) CLLocationManager *locationManager;
@property (nonatomic, strong) MKLocalSearchResponse *response;
@property (weak, nonatomic) IBOutlet MKMapView *mapView;

@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
	
	self.locationManager = [[CLLocationManager alloc] init];
	self.locationManager.delegate = self;
	self.locationManager.distanceFilter = 10; //Expressed in meters.
	self.locationManager.desiredAccuracy = 5; //Also expressed in meters.
	[self.locationManager startUpdatingLocation];
}

#pragma mark - CLLocationManagerDelegate
-(void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations
{
	CLLocation *location = locations.lastObject;
	CLLocationCoordinate2D coordinate = location.coordinate; //This generates for coordinate for a 2D view a set of coordinates from the last object of the locations array.
	MKCoordinateRegion region = MKCoordinateRegionMakeWithDistance(coordinate, 250, 250); //Latitude and Longitude for the region distplayed in the mapview.
	[self.mapView setRegion:region animated:YES]; //Sets the region of the mapview to the region specified above, it is animated (does this do the room thing?).
	
	NSLog(@"Last Object:\n%@\n", locations.lastObject); //This outputs information on the object.
}

#pragma mark - Search Bar Delegate
-(void)searchBarSearchButtonClicked:(UISearchBar *)searchBar
{
	MKLocalSearchRequest *request = [MKLocalSearchRequest new];
	
	[request setRegion:self.mapView.region];
	[request setNaturalLanguageQuery:searchBar.text];
	
	MKLocalSearch *search = [[MKLocalSearch alloc] initWithRequest:request];
	
	[[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES]; //This makes it known to the user that the Network is being used.
	
//	Method with a completion block, this block has two properties, the response and if there is no response the error that will be returned.
	[search startWithCompletionHandler:^(MKLocalSearchResponse *response, NSError *error) {
		[[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:NO]; //Stopping and hiding spinner in the status bar.
		
		if (error) {
			NSLog(@"%@", [error localizedDescription]);
			return;
		}
		
		if (!response.mapItems.count) {
			NSLog(@"No Results Found");
			return;
		}
		
		self.response = response;
	}];
	
}

#pragma mark - UITableViewDataSource
//Required methods for UITableViewDataSource
//These methods are going to be used by the tableview that is generated by the Search Bar receiving information on what is nearby.
-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
	return [self.response.mapItems count];
}
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
//	Is this the default setting for a TableViewCell?
	static NSString *identifier = @"identifier";
	
	UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:identifier];
	
	if (!cell) {
		cell= [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:identifier];
	}
	
	MKMapItem *item = self.response.mapItems[indexPath.row];
	cell.textLabel.text =item.name;
	cell.detailTextLabel.text = item.placemark.addressDictionary[@"Street"];
	
	return cell;
}


#pragma mark - UITableViewDelegate
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
	[self.searchDisplayController setActive:NO animated:YES];
	[self.mapView addAnnotation:[self.response.mapItems[indexPath.row] placemark]];
//	When written, the second method had the autocomplete for placemark struckthrough. Was this because the property is read-only or because it is deprecated. This is weird because 
}


@end
